### ISSUE TITLE
Extend FQM to work in Firefox, Opera, Edge

### ISSUE THREAD

**Issue by ireade** [ireade/feature-queries-manager#1]
The code as it currently exists works fine in Chrome. However, when I try to test in Firefox, I see the following issues:

- `browser.tabs` is not defined in `panel.js`
- If I change the communication from `browser.tabs` to `browser.runtime`, I see an error that the "receiving end does not exist"

**Comment by bwinton** [comment]
Hi @ireade!

So, I heard about your add-on from some Firefox DevTools people, and wondered why stuff wasn't working, so I dug into it a little, and here's what I found.

The [chrome documentation](https://developer.chrome.com/extensions/devtools_panels#overview) says:
> Each extension panel and sidebar is displayed as a separate HTML page. All extension pages displayed in the Developer Tools window have access to all modules in chrome.devtools API, as well as to chrome.extension API. Other extension APIs are not available to the pages within Developer Tools window, but you may invoke them by sending a request to the background page of your extension, similarly to how it's done in the content scripts.

So in theory, your code shouldn't work in Chrome either. I [filed a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1453343) to see whether we want to continue to follow the spec, or change to be compatible with Chrome.

For the second part, it looks like you need a `BROWSER.runtime.onMessage.addListener(function(message, sender, sendResponse) {…};` in your `devtools\devtools.js` and then use that script to communicate between the activeTab and the devtools panel… Does that all make sense?

**Comment by ireade** [comment]
Hi @bwinton !

Thanks so much for your help. I'm going to try this right away, and hopefully it should work!

**Comment by ireade** [comment]
It's done! See PR above. You were correct that the issue was me trying to communicate directly between `panel.js` and `content.js`, but the middleman is actually supposed to be a background script, not eh `devtools.js` file. So I changed some things, and now this works! Thanks again for all your help @bwinton
