### ISSUE TITLE
How to deal with `@supports not` rules that aren’t active in modern browsers

### ISSUE THREAD

**Issue by simevidas** [ireade/feature-queries-manager#4]
This extension enables deactivating styles in feature queries that evaluate to `true` in the browser, e.g.,

```css
@supports (display: grid) {
  /* FQM can deactivate these styles in modern browsers */
}
```

But the extension cannot activate styles in feature queries that evaluate to `false` in the browser (i.e., the opposite case), e.g., 

```css
@supports not (display: grid) {
  /* FQM can’t activate these styles in modern browsers */
}
```

A website may want to use both types of feature queries when enhancing a page layout with Grid, so It may be useful to be able to activate `not (display: grid)` styles to fully emulate the page layout in IE and older Edge.

That being said, this is probably an edge case. I’d suggest waiting until somebody reports that they’re actually using `not (display: grid)` queries.

**Comment by ireade** [comment]
Hey @simevidas !

This is a very good point. I have been thinking of how to handle it. One method I'm considering is that FQM shouldn't delete the rules, it should just "invert" them, by adding/removing a `not` in the feature query. What do you think of this?

**Comment by simevidas** [comment]
Yes, inverting sounds like a more robust solution, in general. The extension could have an “Invert” button (or equivalent icon button) for each feature query, instead of the checkbox. That would make more sense, I think.

 It would probably also be easier for developers to use; for example, they would just have to invert all feature queries containing the `grid` value to get the page layout for IE/old Edge, without having to figure out what the effect of unchecking a query containing `not` is (double negative).

**Comment by ireade** [comment]
Great! I'll give this a try

**Comment by ireade** [comment]
Done! See the README or the gif below for how it works:

![](https://user-images.githubusercontent.com/8677283/39296696-81c1141e-4939-11e8-9c0a-ef92783c57ae.gif)

**Comment by simevidas** [comment]
It’s too confusing for me; I have a problem with logic in complex cases 😅

<img width="639" alt="screen shot 2018-04-28 at 4 56 09 pm" src="https://user-images.githubusercontent.com/716405/39397953-7e61a002-4b07-11e8-907c-5896353cf6ef.png">

I think, my problem is that the UI doesn’t tell me which feature queries evaluate to `true` and which ones to `false` in my browser *by default*.

In the screenshot above, the first one is `true` and the second one `false` in Firefox. So, un-checking the first checkbox *deactivates* the styles that apply by default, while un-checking the second checkbox activates the styles that *don’t* apply by default. In other words, the state of the checkbox does not correspond to whether the styles are applied. I get a mental block from this, since my intuition tells me that a a checked checkbox means “apply styles.”

I’m sorry, I don’t have a better solution. I’m trying to think of a way to make the UI more intuitive, but I can’t come up with anything. For now, as long as I remember that I have to un-check all checkboxes containing `grid` in order to test no grid support, I should be fine.

**Edit:** What if there was a right-aligned `true`/`false` label that showed the value of the feature query in the browser? In addition to that, all checkboxes would be *un-checked* initially, and you would check the ones that you want to invert (still the same issue I mentioned above, but I think check = invert is more intuitive). Also, checking would *not* add a `not ()` wrapper or change the label, since that makes the UI more confusing, I think. Whether or not a feature query is inverted would be solely represented by the checkbox.

**Comment by ireade** [comment]
I totally understand the confusion! 

> I think, my problem is that the UI doesn’t tell me which feature queries evaluate to true and which ones to false in my browser by default.

The problem here isn't actually about whether the feature query evaluates to `true` or `false`, it's about whether the feature query as your wrote it applies or not. Because the former would involve me also knowing what features that the browser you are using with FQM supports, which is another level of complexity. 

My aim here is just for you to reverse whatever query you have written, which is why I wrap it in a "not" statement. 

> For now, as long as I remember that I have to un-check all checkboxes containing grid in order to test no grid support, I should be fine.

The problem with looking at it this way is that it doesn't take into account `not` feature queries, which would mean the _opposite_ of that. If you did write a feature query like `@supports not (display: grid)`, then unchecking the box will mean that the styles within the block would be applied because I'm assuming your browser actually does support feature queries. See the confusion? haha

---

I think a potential solution would be to add extra information on the right side of the extension panel. That could have information on whether your current browser does/doesn't support the feature and information on if the styles are applied or not.

**Comment by simevidas** [comment]
>> For now, as long as I remember that I have to un-check all checkboxes containing grid in order to test no grid support, I should be fine.

> The problem with looking at it this way is that it doesn't take into account not feature queries, which would mean the opposite of that. If you did write a feature query like @supports not (display: grid), then unchecking the box will mean that the styles within the block would be applied because I'm assuming your browser actually does support feature queries. See the confusion? haha

But my approach *does* take into account `not` queries, I think. 

In my screenshot above, if the browser supports `display: grid`, only the first query is `true`, and if the browser doesn’t support it, only the second query is `true`. Hence, if I’m testing in Firefox, and I want to check the page layout when Grid isn’t supported (e.g., how it would render in IE), I have to un-check *both* checkboxes, which flips the first one from `true` to `false`, and the second one from `false` to `true`, thus fully emulating IE.

So, to test the “no grid support” layout, you have to un-check *all* queries that contain `grid`, regardless of whether they contain `not`. Is this correct?

**Comment by ireade** [comment]
> So, to test the “no grid support” layout, you have to un-check all queries that contain grid, regardless of whether they contain not. Is this correct?

It still depends on how you write your feature queries. For example, let's say you have the following code:

```css
#foo { background-color: pink; }

@supports not ( display: grid ) { #foo { background-color: blue; } }
```

Assuming you're in a browser that _does_ support flexbox, then the background colour will be pink.

If you uncheck the checkbox in FQM, then it will turn your feature query to: `@supports not( not ( display: grid ) )`, which essentially is equivalent to `@supports (display grid)`, then the background colour will be blue.

So "unchecking" the checkbox doesn't show "no grid support" in this case. In this case, it does show grid support.

This is why I say it depends on how you write your feature queries. You can't just uncheck all that contain grid in them if you're writing your feature queries in the opposite way.

**Comment by simevidas** [comment]
In the above example, there are two states: `pink`, which represents grid support, and `blue`, which represents no grid support. So for example, Firefox is in the `pink` state, and IE is in the `blue` state.

FQM allows developers to emulate the `blue` state (no grid support) without having to open the page in a browser that actually doesn’t support grid. In order to do that, the developer has to un-check *all* feature queries that contain `grid`, including the ones that start with `not`. Is this not true? 

For example, let’s say you’re testing a page that includes a bunch of `grid` feature queries, and some of these queries start with `not`. Now, if you want the page to render like it would in IE, you have to un-check *all* of those feature queries. It doesn’t matter that some of them have `not`; you still have to un-check all of them to fully emulate “no grid support.”

**Comment by ireade** [comment]
If you reverse a feature query that has a `not` in front of it, what you are emulating is a state in which there *is* grid support, not a state in which there *isn't* grid support.

Let's take the example I wrote above. (we're assuming FQM works in IE which is probably doesn't 😛, also assuming that `@supports` queries work in IE which they definitely don't)

- By default, in Firefox the colour will be pink
- By default, in IE (<10) the colour will be blue
- Unchecking the box in FQM, in Firefox the colour will be blue
- Unchecking the box in FQM, in IE the colour will still be blue

So in this case, unchecking the box will show styles for if `display: flex` IS supported, because the feature query block is based on `display: flex` NOT being supported.

This is why your statement that checking the state of if a feature is not supported by unchecking the checkbox is not always correct. Because if you uncheck the checkbox for a `not` feature query, you're essentially turning it into a state in which, for the styles to be applied, the feature must actually be supported.

**Comment by simevidas** [comment]
**Note:** I’m only responding to your first sentence, because we need to agree on this key detail first (or we need to at least figure out why we *don’t* agree on this detail).

> If you reverse a feature query that has a `not` in front of it, what you are emulating is a state in which there is grid support, not a state in which there isn't grid support.

This is just not true. I will try to explain why I think that. Let’s take the following example:

```css
h1::before {
  content: "Default text";
}

@supports not (display: grid) {
  h1::before {
    content: "Text when grid ISN’T supported";
  }
}
```

## The result if the browser supports Grid

<img width="727" alt="screen shot 2018-05-02 at 4 21 04 pm" src="https://user-images.githubusercontent.com/716405/39528615-dc02ecdc-4e24-11e8-81f9-acebd6040181.png">

## The result if the browser doesn’t support Grid

(The screenshot is Edge 14 via BrowserStack.)

<img width="732" alt="screen shot 2018-05-02 at 4 23 54 pm" src="https://user-images.githubusercontent.com/716405/39528788-5a3d6ab4-4e25-11e8-9858-ed9d0c4f9464.png">

## What happens when I reverse the feature query via FQM

<img width="741" alt="screen shot 2018-05-02 at 4 25 19 pm" src="https://user-images.githubusercontent.com/716405/39528839-804f966e-4e25-11e8-9b96-4d6204bf3475.png">

***

So, by reversing the feature query, I am emulating Edge 14, which *doesn’t* support Grid. In other words, I am emulating a “a state in which there isn’t grid support,” but you said the opposite. Is there anything wrong with my assessment?

P.S. I am sorry if you feel I’m wasting your time. It’s unfortunate that we are having this communication issue.

**Comment by ireade** [comment]
Thanks @simevidas ! I think I see where we are having miscommunication here. 

You have the following feature query:

```css
@supports not (display: grid) {
    /* styles for Edge 14 */
}
```

If you view this page in Firefox you normally wouldn't see those styles, but if you use FQM to invert the rule, then you will see those styles.

So your statement that you are emulating where there *isn't* grid support is true in this sense.

My point was that, FQM actually turns that feature query into essentially this:

```css
@supports (display: grid) {
    /* styles for Edge 14 */
}
```

This means that if you were using FQM in a browser that actually doesn't support `display:grid`, e.g. Edge 14, then those styles will not show.

So my point was that FQM will turn a negative feature query into a positive one. And any difference you see visually will depend on your browser actually supporting said feature in the first place. 

---

On a separate note I agree with your point about not being able to easily tell if your styles are applied or not, so I'm working on a way to show this visually as well.
